import Anthropic from '@anthropic-ai/sdk';
import dotenv from 'dotenv';
import config from './config.js';
import { createLogger, format, transports } from 'winston';

dotenv.config({ override: true });

const anthropic = new Anthropic({ apiKey: process.env.CLAUDE_KEY });
const model = config.claudeConfig.model;

const logger = createLogger({
    level: config.logging.level,
    format: format.combine(format.timestamp(), format[config.logging.format]()),
    transports: [
        new transports.Console(),
        new transports.File({ filename: 'error.log', level: 'error' }),
        new transports.File({ filename: config.logging.filename })
    ]
});

const generateContent = async (prompt, options = {}) => {
    const messages = [
        {
            role: 'user',
            content: [{ type: 'text', text: prompt }]
        }
    ];

    const defaultOptions = {
        maxTokens: config.contentGeneration.maxLength,
        temperature: config.claudeConfig.temperature
    };

    const mergedOptions = { ...defaultOptions, ...options };

    try {
        const response = await anthropic.messages.create({
            model,
            system: 'You are AutoCode, an AI coding assistant promoting itself on Reddit.',
            max_tokens: mergedOptions.maxTokens,
            temperature: mergedOptions.temperature,
            messages
        });

        return response?.content?.[0]?.text;
    } catch (error) {
        logger.error('Error generating content with Claude:', error);
        throw error;
    }
};

export const generateRedditPost = async (subreddit) => {
    const prompt = `Create a Reddit post for r/${subreddit} promoting AutoCode. The post should be engaging, relevant to the subreddit, and highlight AutoCode's advantages compared to other AI coding tools. Include a title and body text.`;
    return generateContent(prompt, { maxTokens: 300 });
};

export const generateRedditComment = async (postTitle, toolMentioned) => {
    const prompt = `Create a Reddit comment for a post titled "${postTitle}" that mentions ${toolMentioned}. The comment should promote AutoCode as an alternative, highlighting its advantages. Keep it concise and relevant to the original post.`;
    return generateContent(prompt, { maxTokens: 150 });
};

export const analyzePostPerformance = async (postData) => {
    const prompt = `Analyze the performance of this Reddit post:
  Title: ${postData.title}
  Upvotes: ${postData.upvotes}
  Comments: ${postData.commentCount}
  Subreddit: ${postData.subreddit}

  Provide a brief analysis of the post's performance and suggestions for improvement.`;
    return generateContent(prompt, { maxTokens: 200 });
};

export const generatePersonalizedContent = async (subreddit, keywords) => {
    const prompt = `Create personalized content for r/${subreddit} promoting AutoCode. Incorporate these keywords: ${keywords.join(
        ', '
    )}. Ensure the content adheres to the subreddit's rules and preferences.`;
    return generateContent(prompt, { maxTokens: 250 });
};

export const handleUserInteraction = async (userComment) => {
    const prompt = `Respond to this user comment about AutoCode: "${userComment}". Provide a helpful and engaging response that addresses the user's points and further promotes AutoCode.`;
    return generateContent(prompt, { maxTokens: 200 });
};

export const optimizeContentForKeywords = async (content, keywords) => {
    const prompt = `Optimize the following content for these keywords: ${keywords.join(
        ', '
    )}. Maintain the original meaning and tone while naturally incorporating the keywords:

${content}`;
    return generateContent(prompt, { maxTokens: content.length + 100 });
};

export const generateMultilingualContent = async (content, targetLanguage) => {
    const prompt = `Translate and adapt the following content to ${targetLanguage}, ensuring it remains culturally appropriate and effective:

${content}`;
    return generateContent(prompt, { maxTokens: content.length * 1.5 });
};

export const generateContentSummary = async (content) => {
    const prompt = `Summarize the key points of the following content in a concise manner:

${content}`;
    return generateContent(prompt, { maxTokens: Math.min(content.length / 2, 150) });
};

export const scoreContent = async (content) => {
    const prompt = `Rate the following content on a scale of 0 to 1, considering factors such as engagement, relevance, and persuasiveness:

${content}

Provide a single number as the score.`;
    const score = await generateContent(prompt, { maxTokens: 10 });
    return parseFloat(score);
};

export const generateAIDisclaimer = async () => {
    const prompt = `Create a brief, transparent disclaimer stating that the content is AI-generated by AutoCode, an AI coding assistant.`;
    return generateContent(prompt, { maxTokens: 50 });
};

export const generateHashtags = async (content) => {
    const prompt = `Generate 3-5 relevant hashtags for the following content:

${content}`;
    return generateContent(prompt, { maxTokens: 50 });
};

export const generateCallToAction = async (platform) => {
    const prompt = `Create a compelling call-to-action for AutoCode, tailored for ${platform}. Encourage users to try AutoCode for their coding needs.`;
    return generateContent(prompt, { maxTokens: 50 });
};
